config/routes.rb
ContactManager::Application.routes.draw do
  root to: 'site#index'

  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get "/login" => redirect("/auth/twitter"), as: :login
  get "/auth/twitter/callback" => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

end

app/models/person.rb
class Person < ActiveRecord::Base
  include Contact
  validates :first_name, :last_name, presence: true
  belongs_to :user

  def to_s
    "#{last_name}, #{first_name}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = current_user.people
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = current_user.people.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :user_id)
    end
end

app/views/people/_form.html.haml
= simple_form_for(@person) do |f|
  = f.error_notification

  .form-group
    = f.input :first_name, input_html: {class: 'form-control'}
  .form-group
    = f.input :last_name, input_html: {class: 'form-control'}

  .form-group
    = f.button :submit, class: 'btn-primary'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 People List

%table.table
  %tr
    %th Name
    %th

  - @people.each do |person|
    %tr
      %td= "#{person.to_s}"
      %td
        %ul.list-inline.actions
          %li= link_to 'Show', person
          %li= link_to 'Edit', edit_person_path(person)
          %li= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path, id: "new_person"

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
- content_for :title do
  - "#{@person.first_name} #{@person.last_name}"

%p#notice= notice

.person
  %h2
    = @person.first_name
    = @person.last_name

  = render "phone_numbers/phone_numbers", phone_numbers: @person.phone_numbers

  %p= link_to 'Add phone number', new_phone_number_path(contact_id: @person.id, contact_type: "Person"), id: 'new_phone_number'

  = render "email_addresses/email_addresses", email_addresses: @person.email_addresses

  %p= link_to 'Add email address', new_email_address_path(contact_id: @person.id, contact_type: "Person"), id: 'new_email_address'

  = link_to 'Edit', edit_person_path(@person)
  \|
  = link_to 'Back', people_path