config/routes.rb
ContactManager::Application.routes.draw do
  root to: 'site#index'

  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get "/login" => redirect("/auth/twitter"), as: :login
  get "/auth/twitter/callback" => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  validates :number, :contact_id, :contact_type, presence: true
  belongs_to :contact, polymorphic: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:edit, :update, :destroy]

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phone_number }
      else
        format.html { render action: 'new' }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    person = @phone_number.contact
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to person }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :contact_id, :contact_type)
    end
end

app/views/phone_numbers/_form.html.haml
= simple_form_for(@phone_number) do |f|
  = f.error_notification

  .form-group
    = f.input :number, input_html: {class: 'form-control'}
  .form-group
    = f.input :contact_id, as: :hidden, input_html: {class: 'form-control'}
  .form-group
    = f.input :contact_type, as: :hidden, input_html: {class: 'form-control'}

  .form-group
    = f.button :submit, class: 'btn-primary'

app/views/phone_numbers/_phone_numbers.html.haml
%p Phone Numbers:
%ul.actions
  - phone_numbers.each do |phone|
    %li
      = phone.number
      = link_to 'edit', edit_phone_number_path(phone)
      \|
      = link_to 'delete', phone_number_path(phone), method: :delete

app/views/phone_numbers/edit.html.haml
%h1= "Editing phone number for #{@phone_number.contact}"

= render 'form'

= link_to 'Show', @phone_number
\|
- if @phone_number.contact_type == "Person"
  = link_to 'Back', phone_numbers_path
- else
  = link_to 'Back', companies_path
\|
- if @phone_number.contact_type == "Person"
  = link_to 'Back to Person', person_path(@phone_number.contact_id)
- else
  = link_to 'Back to Company', company_path(@phone_number.contact_id)

app/views/phone_numbers/new.html.haml
%h1= "New phone number for #{@phone_number.contact}"

= render 'form'

= link_to 'Back', phone_numbers_path
\|
- if @phone_number.contact_type == "Person"
  = link_to 'Back to Person', person_path(@phone_number.contact_id)
- else
  = link_to 'Back to Company', company_path(@phone_number.contact_id)