config/routes.rb
ContactManager::Application.routes.draw do
  root to: 'site#index'

  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get "/login" => redirect("/auth/twitter"), as: :login
  get "/auth/twitter/callback" => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

end

app/models/company.rb
class Company < ActiveRecord::Base
  include Contact
  validates :name, presence: true
  belongs_to :user

  def to_s
    "#{name}"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = current_user.companies
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = current_user.companies.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :user_id)
    end
end

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  = f.error_notification

  .form-group
    = f.input :name, input_html: {class: "form-control"}

  .form-group
    = f.button :submit, class: "btn btn-primary"

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Companies List

%table.table
  %tr
    %th Name
    %th

  - @companies.each do |company|
    %tr
      %td= company.name
      %td
        %ul.list-inline.actions
          %li= link_to 'Show', company
          %li= link_to 'Edit', edit_company_path(company)
          %li= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Company', new_company_path, id: "new_company"

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
- content_for :title do
  = @company.name

%p#notice= notice

.company
  %h2= @company.name

  = render "phone_numbers/phone_numbers", phone_numbers: @company.phone_numbers

  %p= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id, contact_type: "Company"), id: 'new_phone_number'

  = render "email_addresses/email_addresses", email_addresses: @company.email_addresses

  %p= link_to 'Add email address', new_email_address_path(contact_id: @company.id, contact_type: "Company"), id: "new_email_address"

  = link_to 'Edit', edit_company_path(@company)
  \|
  = link_to 'Back', companies_path