config/routes.rb
ContactManager::Application.routes.draw do
  root to: 'site#index'

  resources :companies

  resources :email_addresses, except: [:show, :index]

  resources :phone_numbers, except: [:show, :index]

  resources :people

  get "/login" => redirect("/auth/twitter"), as: :login
  get "/auth/twitter/callback" => 'sessions#create'
  delete "/logout" => "sessions#destroy", as: :logout

end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_action :set_email_address, only: [:edit, :update, :destroy]

  # GET /email_addresses/new
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /email_addresses/1/edit
  def edit
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(email_address_params)

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @email_address }
      else
        format.html { render action: 'new' }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_addresses/1
  # PATCH/PUT /email_addresses/1.json
  def update
    respond_to do |format|
      if @email_address.update(email_address_params)
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    contact = @email_address.contact
    @email_address.destroy
    respond_to do |format|
      format.html { redirect_to contact }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_address
      @email_address = EmailAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_address_params
      params.require(:email_address).permit(:address, :contact_id, :contact_type)
    end
end

app/views/email_addresses/_email_addresses.html.haml
%p Email Addresses:
%ul.actions
  - email_addresses.each do |email|
    %li
      = email.address
      = link_to 'edit', edit_email_address_path(email), id: "edit_email"
      \|
      = link_to 'delete', email_address_path(email), method: :delete, id: "delete_email"

app/views/email_addresses/_form.html.haml
= simple_form_for(@email_address) do |f|
  = f.error_notification

  .form-group
    = f.input :address, input_html: {class: 'form-control'}
  .form-group
    = f.input :contact_id, as: :hidden, input_html: {class: 'form-control'}
  .form-group
    = f.input :contact_type, as: :hidden, input_html: {class: 'form-control'}

  .form-group
    = f.button :submit, class: 'btn-primary'

app/views/email_addresses/edit.html.haml
%h1= "Edit email address for #{@email_address.contact}"

= render 'form'

= link_to 'Show', @email_address
\|
= link_to 'Back', email_addresses_path
\|
- if @email_address.contact_type == "Person"
  = link_to 'Back to Person', person_path(@email_address.contact_id)
- else
  = link_to 'Back to Company', company_path(@email_address.contact_id)

app/views/email_addresses/new.html.haml
%h1= "New email address for #{@email_address.contact}"

= render 'form'

= link_to 'Back', email_addresses_path
\|
- if @email_address.contact_type == "Person"
  = link_to 'Back to Person', person_path(@email_address.contact_id)
- else
  = link_to 'Back to Company', company_path(@email_address.contact_id)